version: "2"
services:
  etherpad:
    image: unihalle/etherpad-lite:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ETHERPAD_TITLE
      - ETHERPAD_DEFAULT_PAD_TEXT
      - ETHERPAD_PORT=9001
      - ETHERPAD_ADMIN_PASSWORD
      - ETHERPAD_ADMIN_USER
      - ETHERPAD_DB_HOST
      - ETHERPAD_DB_PORT
      - ETHERPAD_DB_USER
      - ETHERPAD_DB_PASSWORD
      - ETHERPAD_DB_NAME
      - ETHERPAD_DB_CHARSET
      - ETHERPAD_API_KEY
      - ETHERPAD_SESSION_REQUIRED
      - ETHERPAD_USER_NAME
      - ETHERPAD_USER_PASSWORD
    ports:
      - "127.0.0.1:${ETHERPAD_HOST_PORT}:9001"

  mariadb:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=${ETHERPAD_DB_NAME}
      - MYSQL_USER=${ETHERPAD_DB_USER}
      - MYSQL_PASSWORD=${ETHERPAD_DB_PASSWORD}
    command: ["mysqld", "--character-set-server=${ETHERPAD_DB_CHARSET}", "--collation-server=${ETHERPAD_DB_CHARSET}_unicode_ci"]

